#!/bin/bash

CONF_FILE="$HOME/.gnupg/subkey_map.conf"
SED_OPTIONS=""
GPG_COMMAND='/usr/bin/gpg2'
ARGS="$@"

if (echo "$@" | grep '\-u \|\--local-user ' &>/dev/null) && [ -f $CONF_FILE ]; then
	while read line; do
		primary=$(echo "$line" | sed -e 's/^[ \t]*\([^[:space:]]\+\).*/\1/')
		subkey=$(echo "$line" | sed -e 's/^[ \t]*[^[:space:]]\+\s*\([^[:space:]]\+\).*/\1/')
	
		SED_OPTIONS="$SED_OPTIONS -e 's/-u *$primary/-u $subkey\!/g'"
	done < <(cat "$CONF_FILE" | grep -v '^#' | grep -v '^[ |\t]*$')
	
	ARGS="$(echo $ARGS | eval sed $SED_OPTIONS)"
fi

$GPG_COMMAND $ARGS
exit $?
